---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "keycloak.fullname" . }}-404
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: public-nginx-ingress-default-backend.kube-system.svc.cluster.local
  ports:
    - port: 80
