releases:
    - name: accountapp
      namespace: accountapp
      chart: ../charts/accountapp
      wait: true
      timeout: 300
      force: false
      atomic: true
      values:
        - "../config/default/accountapp.yaml"
      secrets:
        - "../secrets/config/accountapp/secrets.yaml"
