helmDefaults:
  atomic: true
  force: false
  timeout: 600
  wait: true

releases:
    - name: archives
      chart: ../charts/mirror
      namespace: archives
      values:
        - "../config/default/archives.yaml"
      secrets:
        - "../secrets/config/archives/secrets.yaml"
