releases:
    - name: chatbot
      namespace: chatbot
      chart: ../charts/chatbot
      wait: true
      timeout: 300
      force: false
      atomic: true
      values:
        - "../config/default/chatbot.yaml"
      secrets:
        - "../secrets/config/chatbot/secrets.yaml"
