repositories:
- name: falco
  url: https://falcosecurity.github.io/charts
releases:
- name: falco
  namespace: falco
  chart: falco/falco
  version: 0.21.0
  wait: true
  timeout: 100
  atomic: true
  values:
  - "../config/default/falco.yaml"
