repositories:
- name: stable
  url: https://hub.helm.sh/charts
releases:
- name: falco
  namespace: falco
  chart: stable/falco
  version: 0.21.0
  wait: true
  timeout: 100
  atomic: true
  values:
  - "../config/default/falco.yaml"
