releases:
    - name: grafana
      namespace: grafana
      chart: stable/grafana
      wait: true
      timeout: 300
      atomic: true
      values:
        - "../config/default/grafana.yaml"
      secrets:
        - "../secrets/config/grafana/secrets.yaml"
bases:
  - 00-repositories.yaml