repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
    - name: grafana
      namespace: grafana
      chart: stable/grafana
      version: 5.3.0
      wait: true
      timeout: 300
      atomic: true
      values:
        - "../config/default/grafana.yaml"
      secrets:
        - "../secrets/config/grafana/secrets.yaml"
