helmDefaults:
  atomic: true
  force: false
  timeout: 600
  wait: true

releases:
    - name: jenkins-infra
      chart: ../charts/jenkins
      namespace: jenkins-infra
      values:
        - "../config/default/jenkins-infra.yaml"
      secrets:
        - "../secrets/config/jenkins-infra/jenkins.yaml"
      set:
        - name: namespace
          value: jenkins-infra
