releases:
    - name: jenkinsio
      namespace: jenkinsio
      chart: ../charts/jenkinsio
      wait: true
      timeout: 300
      force: false
      atomic: true
      values:
        - "../config/default/jenkinsio.yaml"
      secrets:
        - "../secrets/config/jenkinsio/secrets.yaml"
