releases:
    - name: jenkins-wiki-exporter
      namespace: jenkins-wiki-exporter
      chart: ../charts/jenkins-wiki-exporter
      wait: true
      timeout: 300
      force: false
      atomic: true
      values:
        - "../config/default/jenkins-wiki-exporter.yaml"
      secrets:
        - "../secrets/config/jenkins-wiki-exporter/secrets.yaml"
