repositories:
  - name: loki
    url: https://grafana.github.io/loki/charts
releases:
  - name: loki
    namespace: loki
    chart: loki/loki
    version: 2.1.1
    wait: true
    timeout: 300
    force: false
    atomic: true
    values:
      - "../config/default/loki.yaml"
