repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: mirrorbits-database
    namespace: mirrorbits
    version: 11.3.0
    chart: bitnami/redis
    wait: true
    timeout: 600
    atomic: true
    values:
      - "../config/default/mirrorbits-database.yaml"
    secrets:
      - "../secrets/config/mirrorbits-database/secrets.yaml"
  - name: mirrorbits
    namespace: mirrorbits
    chart: ../charts/mirrorbits
    wait: true
    timeout: 600
    atomic: true
    values:
      - "../config/default/mirrorbits.yaml"
    secrets:
      - "../secrets/config/mirrorbits/secrets.yaml"
