releases:
  - name: mirrorbits
    namespace: mirrorbits
    chart: ../charts/mirrorbits
    wait: true
    timeout: 600
    atomic: false
    values:
      - "../config/default/mirrorbits.yaml"
    secrets:
      - "../secrets/config/mirrorbits/secrets.yaml"
