releases:
    - name: plugin-site
      namespace: plugin-site
      chart: ../charts/plugin-site
      wait: true
      timeout: 300
      force: false
      atomic: true
      values:
        - "../config/default/plugin-site.yaml"
      secrets:
        - "../secrets/config/plugin-site/secrets.yaml"
