repositories:
- name: loki
  url: https://grafana.github.io/loki/charts
releases:
- name: promtail
  namespace: loki
  chart: loki/promtail
  version: 0.23.3
  wait: true
  timeout: 100
  force: true
  atomic: true
  values:
  - "../config/default/promtail.yaml"
