repositories:
  - name: loki
    url: https://grafana.github.io/loki/charts
releases:
  - name: promtail
    namespace: loki
    chart: loki/promtail
    version: 0.24.0
    wait: true
    timeout: 100
    force: false
    atomic: true
    values:
      - "../config/default/promtail.yaml"
