---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins-wiki-exporter.fullname" . }}
  labels:
{{ include "jenkins-wiki-exporter.labels" . | indent 4 }}
type: Opaque
data:
  confluence_username: {{ .Values.confluence.username | b64enc }}
  confluence_password: {{ .Values.confluence.password | b64enc }}
  github_token: {{ .Values.github.token | b64enc }}
